---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-rds
spec:
  package: index.docker.io/jbw976/provider-aws-rds:v1.21.0-rc.0.51.gde5db998a.dirty
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: index.docker.io/jbw976/provider-aws-ec2:v1.21.0-rc.0.51.gde5db998a.dirty
