apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: sqlclaims.devopstoolkit.live
spec:
  compositeTypeRef:
    apiVersion: devopstoolkit.live/v1alpha1
    kind: SQLClaim
  mode: Pipeline
  pipeline:
  - functionRef:
      name: devops-toolkit-crossplane-sqltest-function
    step: test-function
  - functionRef:
      name: crossplane-contrib-function-status-transformer
    input:
      apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      metadata: {}
    step: crossplane-contrib-function-status-transformer
  - functionRef:
      name: crossplane-contrib-function-kcl
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: KCLInput
      spec:
        source: ""
    step: crossplane-contrib-function-kcl
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
