---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitHubClaim
metadata:
  name: ${{ values.name }}
spec:
  id: ${{ values.name }}
  parameters:
    public: ${{ values.public }}
    registry: ${{ values.registry }}
    app:
      language: ${{ values.app.language }}
      host: ${{ values.app.host }}
      namespace: ${{ values.app.namespace }}
    db:
      enabled: ${{ values.db.enabled }}
      provider: ${{ values.db.provider }}
      version: "${{ values.db.version }}"
    repo:
      user: ${{ values.repo.user }}
    gitops:
      enabled: ${{ values.gitops.enabled }}
      user: ${{ values.gitops.user }}
      repo: ${{ values.gitops.repo }}
    backstage:
      enabled: true
