---
apiVersion: devopstoolkit.live/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  id: my-db
  parameters:
    version: "16.3"
    size: medium
    region: us-east-1
    databases:
      - main
    schemas:
      - database: main
        sql: |
          create table videos (
            id varchar(50) not null,
            description text,
            primary key (id)
          );
          create table comments (
            id serial,
            video_id varchar(50) not null,
            description text not null,
            primary key (id),
            CONSTRAINT fk_videos FOREIGN KEY(video_id) REFERENCES videos(id)
          );
    secrets:
      storeName: aws
      pullRootPasswordKey: db-root-password
      pushToStore: true
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
