apiVersion: devopstoolkit.live/v1beta1
kind: SQL
metadata:
  name: my-db-20250507204404
spec:
  version: '14'
  size: small
  region: eastus
  databases:
  - db-01
  - db-02
  crossplane:
    compositionSelector:
      matchLabels:
        provider: azure-aso
        db: postgresql
