apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-postgresql
  labels:
    provider: azure
    db: postgresql
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQL
  mode: Pipeline
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-patch-and-transform
    step: patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
      resources:
      - base:
          apiVersion: azure.upbound.io/v1beta1
          kind: ResourceGroup
          spec:
            forProvider:
              location: eastus
        patches:
        - type: PatchSet
          patchSetName: metadata
        name: resourcegroup
      - base:
          apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
          kind: Server
          spec:
            forProvider:
              location: eastus
              resourceGroupNameSelector:
                matchControllerRef: true
              storageMb: 5120
              autoGrowEnabled: true
              sslEnforcementEnabled: false
              sslMinimalTlsVersionEnforced: TLSEnforcementDisabled
              administratorLogin: postgres
              administratorLoginPasswordSecretRef:
                key: password
              publicNetworkAccessEnabled: true
            writeConnectionSecretToRef:
              namespace: crossplane-system
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: spec.id
          toFieldPath: spec.writeConnectionSecretToRef.name
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.parameters.version
          toFieldPath: spec.forProvider.version
        - fromFieldPath: spec.parameters.size
          toFieldPath: spec.forProvider.skuName
          transforms:
          - type: map
            map:
              small: B_Gen5_1
              medium: GP_Gen5_2
              large: GP_Gen5_8
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.name
          transforms:
          - type: string
            string:
              fmt: '%s-password'
              type: Format
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.namespace
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.fqdn
          toFieldPath: status.address
        name: server
      - base:
          apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
          kind: FirewallRule
          spec:
            forProvider:
              startIpAddress: 0.0.0.0
              endIpAddress: 255.255.255.255
              resourceGroupNameSelector:
                matchControllerRef: true
              serverNameSelector:
                matchControllerRef: true
        patches:
        - type: PatchSet
          patchSetName: metadata
        name: firewall-rule
      - name: sql-config
        base:
          apiVersion: postgresql.sql.crossplane.io/v1alpha1
          kind: ProviderConfig
          metadata:
            name: default
          spec:
            credentials:
              source: PostgreSQLConnectionSecret
            sslMode: require
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: spec.id
          toFieldPath: spec.credentials.connectionSecretRef.name
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.credentials.connectionSecretRef.namespace
        readinessChecks:
        - type: None
      - name: kubernetes
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha1
          kind: ProviderConfig
          spec:
            credentials:
              source: InjectedIdentity
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: '%s-sql'
              type: Format
        readinessChecks:
        - type: None
      - name: helm
        base:
          apiVersion: helm.crossplane.io/v1beta1
          kind: ProviderConfig
          spec:
            credentials:
              source: InjectedIdentity
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: '%s-sql'
              type: Format
        readinessChecks:
        - type: None
  - functionRef:
      name: crossplane-contrib-function-go-templating
    step: sql-db
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      delims:
        left: '{{'
        right: '}}'
      inline:
        template: |-
          {{ range .observed.composite.resource.spec.parameters.databases }}
          ---
          apiVersion: postgresql.sql.crossplane.io/v1alpha1
          kind: Database
          metadata:
            name: {{ $.observed.composite.resource.spec.id }}-{{ . }}
            annotations:
              crossplane.io/external-name: {{ . }}
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $.observed.composite.resource.spec.id }}-{{ . }}
          spec:
            providerConfigRef:
              name: {{ $.observed.composite.resource.spec.id }}
            forProvider: {}
          {{ end }}
  - functionRef:
      name: crossplane-contrib-function-go-templating
    step: schema
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      delims:
        left: '{{'
        right: '}}'
      inline:
        template: |-
          {{ range .observed.composite.resource.spec.parameters.schemas }}
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $.observed.composite.resource.spec.id }}-schema-{{ .database }}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $.observed.composite.resource.spec.id }}-schema-{{ .database }}
          spec:
            providerConfigRef:
              name: {{ $.observed.composite.resource.spec.id }}-sql
            forProvider:
              manifest:
                apiVersion: db.atlasgo.io/v1alpha1
                kind: AtlasSchema
                metadata:
                  name: {{ $.observed.composite.resource.spec.id }}-{{ .database }}
                  namespace: {{ $.observed.composite.resource.spec.claimRef.namespace }}
                toFieldPath: spec.credentials.connectionSecretRef.namespace
                spec:
                  credentials:
                    scheme: postgres
                    hostFrom:
                      secretKeyRef:
                        key: endpoint
                        name: {{ $.observed.composite.resource.spec.id }}
                    port: 5432
                    userFrom:
                      secretKeyRef:
                        key: username
                        name: {{ $.observed.composite.resource.spec.id }}
                    passwordFrom:
                      secretKeyRef:
                        key: password
                        name: {{ $.observed.composite.resource.spec.id }}
                    database: {{ .database }}
                    parameters:
                      sslmode: disable
                  schema: 
                    sql: "{{ .sql }}"
          {{ end }}
  - functionRef:
      name: crossplane-contrib-function-go-templating
    step: secret-pull
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      delims:
        left: '{{'
        right: '}}'
      inline:
        template: |-
          {{ if and .observed.composite.resource.spec.parameters.secrets.storeName .observed.composite.resource.spec.parameters.secrets.pullRootPasswordKey }}
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $.observed.composite.resource.spec.id }}-secret-pull
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $.observed.composite.resource.spec.id }}-secret-pull
          spec:
            providerConfigRef:
              name: {{ $.observed.composite.resource.spec.id }}-sql
            forProvider:
              manifest:
                metadata:
                  name: {{ $.observed.composite.resource.spec.id }}-password
                  namespace: {{ $.observed.composite.resource.spec.claimRef.namespace }}
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                spec:
                  dataFrom:
                  - extract:
                      conversionStrategy: Default
                      decodingStrategy: None
                      key: {{ $.observed.composite.resource.spec.parameters.secrets.pullRootPasswordKey }}
                      metadataPolicy: None
                  refreshInterval: 1h
                  secretStoreRef:
                    kind: ClusterSecretStore
                    name: {{ $.observed.composite.resource.spec.parameters.secrets.storeName }}
                  target:
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    name: {{ $.observed.composite.resource.spec.id }}-password
          {{ end }}
  - functionRef:
      name: crossplane-contrib-function-go-templating
    step: secret-push-store
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      delims:
        left: '[['
        right: ']]'
      inline:
        template: |-
          [[ if and .observed.composite.resource.spec.parameters.secrets.storeName .observed.composite.resource.spec.parameters.secrets.pushToStore ]]
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: [[ $.observed.composite.resource.spec.id ]]-secret-push-store
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: [[ $.observed.composite.resource.spec.id ]]-secret-push-store
          spec:
            providerConfigRef:
              name: [[ $.observed.composite.resource.spec.id ]]-sql
            forProvider:
              manifest:
                apiVersion: external-secrets.io/v1alpha1
                kind: PushSecret
                metadata:
                  name: [[ $.observed.composite.resource.spec.id ]]
                  namespace: [[ $.observed.composite.resource.spec.claimRef.namespace ]]
                spec:
                  deletionPolicy: Delete
                  refreshInterval: 1h
                  secretStoreRefs:
                    - name: [[ $.observed.composite.resource.spec.parameters.secrets.storeName ]]
                      kind: ClusterSecretStore
                  selector:
                    secret:
                      name: [[ $.observed.composite.resource.spec.id ]]
                  template:
                    data:
                      endpoint: |
                        {
                          "endpoint": "{{ .endpoint }}",
                          "port": "{{ .port }}",
                          "username": "{{ .username }}",
                          "password": "{{ .password }}"[[ range .observed.composite.resource.spec.parameters.databases ]],
                          "conn-[[ . ]]": "host={{ .endpoint }} user={{ .username }} password={{ .password }} port={{ .port }} connect_timeout=10 database=[[ . ]]"[[ end ]]
                        }
                  data:
                    - match:
                        secretKey: endpoint
                        remoteRef:
                          remoteKey: [[ $.observed.composite.resource.spec.id ]]
          [[ end ]]
  - functionRef:
      name: crossplane-contrib-function-go-templating
    step: secret-pull-cluster
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      delims:
        left: '{{'
        right: '}}'
      inline:
        template: |-
          {{ if and .observed.composite.resource.spec.parameters.secrets.storeName .observed.composite.resource.spec.parameters.secrets.pullToCluster }}
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $.observed.composite.resource.spec.id }}-secret-pull-cluster
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $.observed.composite.resource.spec.id }}-secret-pull-cluster
          spec:
            providerConfigRef:
              name: {{ $.observed.composite.resource.spec.parameters.secrets.pullToCluster }}
            forProvider:
              manifest:
                metadata:
                  name: {{ $.observed.composite.resource.spec.id }}
                  namespace: {{ $.observed.composite.resource.spec.parameters.secrets.pullToClusterNamespace }}
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                spec:
                  dataFrom:
                  - extract:
                      conversionStrategy: Default
                      decodingStrategy: None
                      key: {{ $.observed.composite.resource.spec.id }}
                      metadataPolicy: None
                  refreshInterval: 1h
                  secretStoreRef:
                    kind: ClusterSecretStore
                    name: {{ $.observed.composite.resource.spec.parameters.secrets.storeName }}
                  target:
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    name: {{ $.observed.composite.resource.spec.id }}
          {{ end }}
  - functionRef:
      name: crossplane-contrib-function-go-templating
    step: dapr-components
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      delims:
        left: '{{'
        right: '}}'
      inline:
        template: |-
          {{ if and .observed.composite.resource.spec.parameters.secrets.daprComponents .observed.composite.resource.spec.parameters.secrets.pullToCluster }}
          {{ range .observed.composite.resource.spec.parameters.databases }}
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $.observed.composite.resource.spec.id }}-dapr-component-{{ . }}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $.observed.composite.resource.spec.id }}-dapr-component-{{ . }}
          spec:
            providerConfigRef:
              name: {{ $.observed.composite.resource.spec.parameters.secrets.pullToCluster }}
            forProvider:
              manifest:
                apiVersion: dapr.io/v1alpha1
                kind: Component
                metadata:
                  name: {{ $.observed.composite.resource.spec.id }}-{{ . }}
                  namespace: {{ $.observed.composite.resource.spec.parameters.secrets.pullToClusterNamespace }}
                spec:
                  type: state.postgresql
                  version: v1
                  metadata:
                    - name: connectionString
                      secretKeyRef:
                        name: {{ $.observed.composite.resource.spec.id }}
                        key: conn-{{ . }}
          {{ end }}
          {{ end }}
  - functionRef:
      name: crossplane-contrib-function-go-templating
    step: dynatrace
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      delims:
        left: '{{'
        right: '}}'
      inline:
        template: |-
          {{ if .observed.composite.resource.spec.parameters.dynatraceDashboard.enabled }}
          ---
          apiVersion: helm.crossplane.io/v1beta1
          kind: Release
          metadata:
            name: {{ .observed.composite.resource.spec.id }}-dynatrace-dashboard
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.spec.id }}-dynatrace-dashboard
          spec:
            providerConfigRef:
              name: {{ $.observed.composite.resource.spec.parameters.dynatraceDashboard.cluster }}
            forProvider:
              chart:
                name: kubernetes-workload
                repository: https://katharinasick.github.io/crossplane-observability-demo-dynatrace
                version: "0.1.5"
              values:
                oauthCredentialsSecretName: {{ .observed.composite.resource.spec.parameters.dynatraceDashboard.oathCredentialsSecretName }}
                dashboard:
                  enabled: true
                alerting:
                  enabled: true
                  slackChannel: "#{{ .observed.composite.resource.spec.parameters.dynatraceDashboard.slackChannel }}"
                workloadName: {{ .observed.composite.resource.spec.parameters.dynatraceDashboard.appDeploymentName }}
                cluster: {{ .observed.composite.resource.spec.parameters.dynatraceDashboard.cluster }}
                namespace: {{ .observed.composite.resource.spec.parameters.dynatraceDashboard.appNamespace }}
                crossplaneTerraformProvider:
                  connectionSecretRef:
                    name: dynatrace-terraform-creds
                  namespace: crossplane-system
                  key: credentials
                databaseAddress: {{ .observed.composite.resource.status.address }}
              namespace: dynatrace
            providerConfigRef:
              name: {{ .observed.composite.resource.spec.id }}-sql
            rollbackLimit: 3
          {{ end }}
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: automatically-detect-ready-composed-resources
