apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-sql
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/crossplane-sql
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational PostgreSQL database servers, databases, and schemas in AWS, Google Cloud Platform, Azure, UpCloud, and a local in-cluster CNPG.
    meta.crossplane.io/readme: A Configuration package that defines a SQL type that can be used to create and provision fully operational PostgreSQL database servers, databases, and schemas in AWS, Google Cloud Platform, Azure, UpCloud, and a local in-cluster CNPG.
spec:
  crossplane:
    version: ">=v2.0.0"
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-aws-ec2
    version: ">=v1.0.0"
  - provider: xpkg.upbound.io/upbound/provider-aws-rds
    version: ">=v1.0.0"
  - provider: xpkg.upbound.io/upbound/provider-azure-dbforpostgresql
    version: ">=v0.33.0"
  - provider: xpkg.upbound.io/upbound/provider-gcp-sql
    version: ">=v0.33.0"
  - provider: xpkg.upbound.io/upcloud/provider-upcloud
    version: ">=v0.0.7"
  - provider: xpkg.upbound.io/crossplane-contrib/provider-sql
    version: ">=v0.9.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: ">=v0.2.1"
  - function: xpkg.upbound.io/crossplane-contrib/function-status-transformer
    version: ">=v0.3.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-kcl
    version: ">=v0.10.3"
  # - provider: xpkg.upbound.io/upbound/provider-kubernetes
  #   version: ">=v0.11.0"
  # - provider: xpkg.upbound.io/upbound/provider-helm
  #   version: ">=v0.17.0"
