apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-sql
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/crossplane-sql
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational PostgreSQL database servers, databases, and schemas in AWS (Crossplane provider and ACK), Google Cloud Platform, Azure (Crossplane provider and ASO), UpCloud, and a local in-cluster CNPG and with schema management.
    meta.crossplane.io/readme: A Configuration package that defines a SQL type that can be used to create and provision fully operational PostgreSQL database servers, databases, and schemas in AWS (Crossplane provider and ACK), Google Cloud Platform, Azure (Crossplane provider and ASO), UpCloud, and a local in-cluster CNPG, all with schema management.
    description: Production-ready PostgreSQL database service across AWS, GCP, Google Cloud, Azure, and UpCloud and with schema management.
    database.engines: PostgreSQL
    providers: AWS RDS, Google Cloud SQL, Azure Database, UpCloud Managed Database
    keywords: postgresql,mysql,database,multi-cloud,managed-service
spec:
  crossplane:
    version: ">=v2.0.0-preview.1"
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
    version: ">=v2.0.0"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-aws-rds
    version: ">=v2.0.0"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-azure-dbforpostgresql
    version: ">=v2.0.0"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-gcp-sql
    version: ">=v2.0.0"
  - provider: xpkg.upbound.io/upcloud/provider-upcloud
    version: ">=v0.0.7"
  - provider: xpkg.upbound.io/crossplane-contrib/provider-sql
    version: ">=v0.9.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: ">=v0.2.1"
  - function: xpkg.upbound.io/crossplane-contrib/function-status-transformer
    version: ">=v0.3.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-kcl
    version: ">=v0.10.3"
