apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: crossplane-sql
spec:
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-aws-ec2
    version: '>=v1.0.0'
  - provider: xpkg.upbound.io/upbound/provider-aws-rds
    version: '>=v1.0.0'
  - provider: xpkg.upbound.io/upbound/provider-azure-dbforpostgresql
    version: '>=v0.33.0'
  - provider: xpkg.upbound.io/upbound/provider-gcp-sql
    version: '>=v0.33.0'
  - provider: xpkg.upbound.io/upcloud/provider-upcloud
    version: '>=v0.0.7'
  - provider: xpkg.upbound.io/crossplane-contrib/provider-sql
    version: '>=v0.9.0'
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.2.1'
  - function: xpkg.upbound.io/crossplane-contrib/function-status-transformer
    version: '>=v0.3.0'
  - function: xpkg.upbound.io/crossplane-contrib/function-kcl
    version: '>=v0.10.3'
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    Fully operational PostgreSQL database servers, databases, and schemas in AWS, Google Cloud Platform, Azure, and UpCloud.
  repository: xpkg.upbound.io/devops-toolkit/crossplane-sql
  source: github.com/vfarcic/crossplane-sql
