apiVersion: devopstoolkit.live/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
  namespace: a-team
spec:
  id: my-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "16.3"
    size: medium
    region: us-east-1
    databases:
      - db-01
      - db-02
